version: '3.4'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: messengerdb
      MYSQL_USER: messengeruser
      MYSQL_PASSWORD: password
    volumes:
       - dbdata:/var/lib/mysql
    ports:
       - "3306:3306"
    restart: always
    
  server:
    depends_on:
        - db
    image: pwa.server
    build:
      context: CZ.TUL.PWA.Messenger.Server
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
      
volumes:
    dbdata:
