version: '3.4'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: messengerdb
      MYSQL_USER: messengeruser
      MYSQL_PASSWORD: messengeruserpassw0rd
    ports:
      - "3306:3306"
  server:
    depends_on:
        - db
    image: ${DOCKER_REGISTRY-}server
    build:
      context: .
    ports:
      - "443"

