version: '3.4'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: messengerdb
      MYSQL_USER: messengeruser
      MYSQL_PASSWORD: password
    volumes:
       - dbdata:/var/lib/mysql
    restart: always
    
  server:
    depends_on:
        - db
    image: pwa.server
    build:
      context: CZ.TUL.PWA.Messenger.Server
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
      
  client:
    depends_on:
        - server
    image: pwa.client
    build: 
        context: CZ.TUL.PWA.Messenger.Client/cz-tul-pwa-messenger-client
        dockerfile: Dockerfile
    ports:
      - 80:80
      
volumes:
    dbdata:
